// Code generated by Kitex v0.3.4. DO NOT EDIT.

package videoservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/evpeople/douyin/kitex_gen/publish"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetPublishVideos(ctx context.Context, Req *publish.DouyinPublishRequest, callOptions ...callopt.Option) (r *publish.DouyinPublishResponse, err error)
	PostVideos(ctx context.Context, Req *publish.UploadFileRequest, callOptions ...callopt.Option) (r *publish.BaseResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) GetPublishVideos(ctx context.Context, Req *publish.DouyinPublishRequest, callOptions ...callopt.Option) (r *publish.DouyinPublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishVideos(ctx, Req)
}

func (p *kVideoServiceClient) PostVideos(ctx context.Context, Req *publish.UploadFileRequest, callOptions ...callopt.Option) (r *publish.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PostVideos(ctx, Req)
}
