server:
	kitex -I ../../../idl/ -module "github.com/evpeople/douyin" -type protobuf  -use ../../../kitex-gen/register -service register ../../../idl/register.proto 
# server:
# 	kitex -service demonote ../../idl/register.thrift -module